feat: home work 4
Sapendo/ruby_mentoring_program pull request #3
Opened 2021-03-01 00:03 UTC by Sapendo

1) added class user
2) transformed luhn_algorithm to class card_checksum
3) added module validation. It contains one method, but it is used in 2 classes

2021-03-03 08:08 UTC, andy-vin commented on home_work_4/card_checksum.rb
> +    card_number = gets.chomp
Should we use
```bash
@card_number = gets.chomp
```
instead of
```bash
card_number = gets.chomp
@card_number = card_number
```
?

2021-03-03 08:14 UTC, andy-vin commented on home_work_4/card_checksum.rb
> +class CardChecksum
Which pattern you implement, when writing this code?

2021-03-03 08:16 UTC, andy-vin commented on home_work_4/card_checksum.rb
> +    puts run_card_validation
this line should not be here

2021-03-03 08:21 UTC, andy-vin commented on home_work_4/card_checksum.rb
> +  def validation
Split this method on 2:
- validate the card number by digits only
- validate the card number by pattern

2021-03-03 08:27 UTC, andy-vin commented on home_work_4/card_checksum.rb
> +  def checksum_validation(checksum)
if you read the previous home task this method should return:
- `check successful for {NU-M-B-ER}` in a successful case
- error with the details of it (empty string provided, the wrong format of the input, wrong checksum, etc.) in unsuccessful case

2021-03-03 08:28 UTC, andy-vin commented on home_work_4/user.rb
> +    validate_by_regexp(name, NAME_PATTERN, 'Name must contains letters only and be more than 2 characters.')
this line should not be here

2021-03-03 08:29 UTC, andy-vin commented on home_work_4/user.rb
> +    validate_by_regexp(age, AGE_PATTERN, 'Age must contains numbers only. Also your age must between 13 and 119')
this line should not be here

2021-03-03 08:30 UTC, andy-vin commented on home_work_4/user.rb
> +  def check_card
Why user should be able to do this?

Better to move this logic to another class

2021-03-03 08:32 UTC, andy-vin commented on home_work_4/user.rb
> +puts 'Please introduce yourself'
why this should be here?

2021-03-03 08:53 UTC, andy-vin commented
pay attention into:
- Users under 13 y.o. should not be able to check the cards
- Users above 13 are allowed to input the credit card number and to get the results of checksum validation
- The program should log all the actions (user names, ages, and the results of their checks) into a log file

2021-03-07 09:56 UTC, Sapendo commented on home_work_4/card_checksum.rb
> +    card_number = gets.chomp
done

2021-03-08 17:23 UTC, andy-vin commented on home_work_4/dashboard.rb
> +dashboard = Dashboard.new
Move 70-73 lines into a separate file, for example: start.rb

2021-03-08 17:24 UTC, andy-vin approved these changes

2021-03-08 17:25 UTC, andy-vin requested changes
add logging and fix last comment

2021-03-11 15:45 UTC, merged